From wso2/wso2am:4.0.0

COPY apimanager/wso2am-4.0.0/repository/resources/security/client-truststore.jks /home/wso2carbon/wso2am-4.0.0/repository/resources/security/client-truststore.jks
COPY apimanager/wso2am-4.0.0/repository/resources/security/wso2carbon.jks /home/wso2carbon/wso2am-4.0.0/repository/resources/security/wso2carbon.jks
COPY apimanager/wso2am-4.0.0/repository/components/lib/mysql-connector-java-5.1.33.jar /home/wso2carbon/wso2am-4.0.0/repository/components/lib/
COPY apimanager/wso2am-4.0.0/repository/conf/deployment.toml /home/wso2carbon/wso2am-4.0.0/repository/conf/deployment.toml
COPY apimanager/wso2am-4.0.0/repository/components/dropins/org.wso2.carbon.apim.migration.validator-1.0-SNAPSHOT.jar /home/wso2carbon/wso2am-4.0.0/repository/components/dropins/org.wso2.carbon.apim.migration.validator-1.0-SNAPSHOT.jar
