From oracle/database:19.3.0-ee

COPY database/wso2am-3.2.0/dbscripts/oracle.sql /oracle1.sql
COPY database/wso2am-3.2.0/dbscripts/apimgt/oracle.sql /oracle2.sql
COPY database/setup.sql /docker-entrypoint-initdb.d/setup/
