version: '2.1'
services:
 db2:
    image: database2:3.2.0
    build:
         context: ./
         dockerfile: database/Dockerfile
    extra_hosts:
         - "apim:127.0.0.1"
networks: 
  default: 
    external: 
      name: external-Network 
    
