version: '2.1'
services:
 dbpostgres:
    image: databasepostgres:3.2.0
    build:
         context: ./
         dockerfile: database/Dockerfile
    environment:
         POSTGRES_USER: root
         POSTGRES_PASSWORD: pwd
    extra_hosts:
         - "apim:127.0.0.1"
    ports:
         - "5432:5432"
networks: 
  default: 
    external: 
      name: external-Network     
