From wso2/wso2am:3.2.0

COPY apimanager/wso2am-3.2.0/repository/components/lib/mysql-connector-java-5.1.33.jar /home/wso2carbon/wso2am-3.2.0/repository/components/lib/
COPY apimanager/wso2am-3.2.0/repository/conf/deployment.toml /home/wso2carbon/wso2am-3.2.0/repository/conf/deployment.toml
