From postgres

COPY database/wso2am-3.2.0/dbscripts/postgresql.sql /postgresql1.sql
COPY database/wso2am-3.2.0/dbscripts/apimgt/postgresql.sql /postgresql2.sql
COPY database/setup.sql /docker-entrypoint-initdb.d/
